version: 0.0
os: linux
files:
  - source: /
    destination: /new_chatapp

hooks:
  BeforeInstall:
    - location: scripts/remove.sh
      timeout: 500
      runas: ubuntu
  AfterInstall:
    - location: scripts/installationcommands.sh
      timeout: 500
      runas: ubuntu
  ApplicationStart:
    - location: scripts/startproject.sh
      timeout: 500
      runas: ubuntu
